// <auto-generated />
namespace Boligf.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UserFirstAndLastNameRequiredRemoved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserFirstAndLastNameRequiredRemoved));
        
        string IMigrationMetadata.Id
        {
            get { return "201505091412223_UserFirstAndLastNameRequiredRemoved"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
